version: '2'

services:
   postgres:
     build: ./postgres
     container_name: postgres
     ports:
      - "5432:5432"
     restart: always
     environment:
       - POSTGRES_USER=postgres
       - POSTGRES_PASSWORD=123456
     volumes:
       - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
